version: "3"

services:
  web:
    build: .
    ports:
      - "8000:5000"
    environment:
      TOPIC_NAME: "TRANSACTIONS"
      KAFKA_SERVER: "kafka:9092"
      KOWL_SERVER: "localhost:8080"
      LOCAL_INFURA_URL: "http://127.0.0.1:8545"
      PUBLIC_INFURA_URL: $PUBLIC_INFURA_URL
      DEV_MNEMONIC: $DEV_MNEMONIC
      DISCORD_WEBHOOK_URL: $DISCORD_WEBHOOK_URL
      PUBLIC_BLOCKCHAIN: "True"
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: 'bitnami/kafka:latest'
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
      - '9093:9093'

    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT, EXTERNAL:PLAINTEXT
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false

  kowl:
    image: quay.io/cloudhut/kowl:master
    restart: on-failure
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      - KAFKA_BROKERS=kafka:9092

  init-kafka:
    image: confluentinc/cp-kafka:6.1.1
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka:9092 --list

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka:9092 --create --topic TRANSACTIONS --replication-factor 1 --partitions 1

      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka:9092 --list
      "
