from os import environ

TOPIC_NAME = environ.get('TOPIC_NAME')
KAFKA_SERVER = environ.get('KAFKA_SERVER')
KOWL_SERVER = environ.get('KOWL_SERVER')
LOCAL_INFURA_URL = environ.get('LOCAL_INFURA_URL')
PUBLIC_INFURA_URL = environ.get('PUBLIC_INFURA_URL')
DISCORD_WEBHOOK_URL = environ.get('DISCORD_WEBHOOK_URL')
PUBLIC_BLOCKCHAIN = environ.get('PUBLIC_BLOCKCHAIN')